# 0. Identification -------------------------------------------------------

# Title: Metadata file for variables used in Justice and Violence analysis
# Institution: Centro de Estudios de Conflicto y Cohesión Social (COES)
# Responsable: Researcher

# Executive Summary: This script creates an Excel metadata file documenting all variables
# used in the Justice and Violence analysis (processed in 01_proc_elsoc.R)
# Date: March 2026

rm(list = ls())

# 1. Load packages --------------------------------------------------------

if (!require("pacman")) {
  install.packages("pacman")
}

pacman::p_load(
  tidyverse,
  writexl
)

# 2. Create metadata ------------------------------------------------------

metadata <- tribble(
  ~variable       , ~tipo                    , ~descripcion                                                                                                                                                                                                           , ~valores                                                                                                                                                                                             , ~olas_disponibles      , ~rol_en_analisis                     ,
  # --- Identificadores ---
  "idencuesta"    , "Identificador"          , "Identificador único del encuestado en el panel"                                                                                                                                                                       , "Numérico"                                                                                                                                                                                           , "w01-w07"              , "Identificador"                      ,
  "tipo_atricion" , "Identificador"          , "Tipo de atrición del encuestado en el panel longitudinal"                                                                                                                                                             , "Categórica"                                                                                                                                                                                         , "w01-w07"              , "Control de muestra"                 ,
  "tipo_caso"     , "Identificador"          , "Tipo de caso en el panel (muestra original, refresco, etc.)"                                                                                                                                                          , "Categórica"                                                                                                                                                                                         , "w01-w07"              , "Control de muestra"                 ,

  # --- Controles sociodemográficos ---
  "m0_edad"       , "Sociodemográfica"       , "Edad del entrevistado en años cumplidos"                                                                                                                                                                              , "Numérico continuo"                                                                                                                                                                                  , "w01"                  , "Control (tiempo-invariante)"        ,
  "m0_sexo"       , "Sociodemográfica"       , "Sexo del entrevistado"                                                                                                                                                                                                , "1=Hombre; 2=Mujer"                                                                                                                                                                                  , "w01"                  , "Control (tiempo-invariante)"        ,
  "m01"           , "Sociodemográfica"       , "Nivel educacional del entrevistado"                                                                                                                                                                                   , "1=Sin estudios; 2=Básica incompleta; 3=Básica completa; 4=Media incompleta; 5=Media completa; 6=Técnica incompleta; 7=Técnica completa; 8=Universitaria incompleta; 9=Universitaria completa o más" , "w01"                  , "Control (tiempo-invariante)"        ,

  # --- Posicionamiento político ---
  "c15"           , "Política"               , "Posicionamiento político en escala izquierda-derecha"                                                                                                                                                                 , "0=Extrema izquierda; 10=Extrema derecha; 11=Ninguno; 12=NS/NR"                                                                                                                                      , "w01-w07"              , "Base para moderadores ideológicos"  ,

  # --- Variable X principal: Tolerancia a la violencia ---
  "c18_11"        , "Tolerancia a violencia" , "Justificación del uso de violencia física en el contexto de protestas y manifestaciones sociales"                                                                                                                     , "1=Nunca justificado; 2=Pocas veces; 3=Algunas veces; 4=Muchas veces; 5=Siempre justificado"                                                                                                         , "w01-w07"              , "Variable X principal (RI-CLPM)"     ,

  # --- Variables Y: Violencia en protestas / participación contenciosa ---
  "f05_01"        , "Violencia/Protesta"     , "Participación en manifestaciones o marchas (ver codebook ELSOC para texto exacto)"                                                                                                                                    , "0=No; 1=Sí"                                                                                                                                                                                         , "w01-w04"              , "Variable Y (análisis exploratorio)" ,
  "f05_02"        , "Violencia/Protesta"     , "Participación en barricadas o bloqueos de calles (ver codebook ELSOC para texto exacto)"                                                                                                                              , "0=No; 1=Sí"                                                                                                                                                                                         , "w01-w04"              , "Variable Y (análisis exploratorio)" ,
  "f05_03"        , "Violencia/Protesta"     , "Participación en huelgas o paros (ver codebook ELSOC para texto exacto)"                                                                                                                                              , "0=No; 1=Sí"                                                                                                                                                                                         , "w01-w07"              , "Variable Y (análisis exploratorio)" ,
  "f05_04"        , "Violencia/Protesta"     , "Participación en actos de violencia en el contexto de protestas (ver codebook ELSOC para texto exacto)"                                                                                                               , "0=No; 1=Sí"                                                                                                                                                                                         , "w01-w07"              , "Variable Y PRINCIPAL (RI-CLPM)"     ,
  "f05_05"        , "Violencia/Protesta"     , "Participación en ocupaciones de edificios o tomas (ver codebook ELSOC para texto exacto)"                                                                                                                             , "0=No; 1=Sí"                                                                                                                                                                                         , "w01-w04"              , "Variable Y (análisis exploratorio)" ,
  "f05_06"        , "Violencia/Protesta"     , "Daño a propiedad pública o privada en el contexto de protestas (ver codebook ELSOC para texto exacto)"                                                                                                                , "0=No; 1=Sí"                                                                                                                                                                                         , "w01-w07"              , "Variable Y (análisis exploratorio)" ,
  "f05_07"        , "Violencia/Protesta"     , "Agresión física a personas en el contexto de protestas (ver codebook ELSOC para texto exacto)"                                                                                                                        , "0=No; 1=Sí"                                                                                                                                                                                         , "w01-w07"              , "Variable Y (análisis exploratorio)" ,

  # --- Variables Y: Participación política/contenciosa (t06, t09) ---
  "t06_01"        , "Participación política" , "Participación política contenciosa - ítem 1 (ver codebook ELSOC para texto exacto)"                                                                                                                                   , "Escala Likert o dicotómica (ver codebook)"                                                                                                                                                          , "w01-w04"              , "Variable Y (análisis exploratorio)" ,
  "t09_01"        , "Participación política" , "Participación política contenciosa - ítem 1 módulo t09 (ver codebook ELSOC para texto exacto)"                                                                                                                        , "Escala Likert o dicotómica (ver codebook)"                                                                                                                                                          , "w01-w07"              , "Variable Y (análisis exploratorio)" ,
  "t09_02"        , "Participación política" , "Participación política contenciosa - ítem 2 módulo t09 (ver codebook ELSOC para texto exacto)"                                                                                                                        , "Escala Likert o dicotómica (ver codebook)"                                                                                                                                                          , "w01-w07"              , "Variable Y (análisis exploratorio)" ,
  "t09_03"        , "Participación política" , "Participación política contenciosa - ítem 3 módulo t09 (ver codebook ELSOC para texto exacto)"                                                                                                                        , "Escala Likert o dicotómica (ver codebook)"                                                                                                                                                          , "w01-w07"              , "Variable Y (análisis exploratorio)" ,

  # --- Variables para brecha salarial (intermedias) ---
  "d03_01"        , "Desigualdad"            , "Salario mensual percibido para el trabajador o profesional mejor remunerado en Chile (ej. gerente)"                                                                                                                   , "Numérico continuo (pesos chilenos)"                                                                                                                                                                 , "w01-w07"              , "Insumo para brecha_perc"            ,
  "d03_02"        , "Desigualdad"            , "Salario mensual percibido para el trabajador peor remunerado en Chile (ej. obrero no calificado)"                                                                                                                     , "Numérico continuo (pesos chilenos)"                                                                                                                                                                 , "w01-w07"              , "Insumo para brecha_perc"            ,
  "d04_01"        , "Desigualdad"            , "Salario mensual justo para el trabajador o profesional mejor remunerado en Chile"                                                                                                                                     , "Numérico continuo (pesos chilenos)"                                                                                                                                                                 , "w01-w07"              , "Insumo para brecha_just"            ,
  "d04_02"        , "Desigualdad"            , "Salario mensual justo para el trabajador peor remunerado en Chile"                                                                                                                                                    , "Numérico continuo (pesos chilenos)"                                                                                                                                                                 , "w01-w07"              , "Insumo para brecha_just"            ,

  # --- Percepción de justicia en servicios públicos ---
  "d02_01"        , "Justicia distributiva"  , "Percepción de justicia en el sistema de pensiones en Chile"                                                                                                                                                           , "1=Completamente injusto; 5=Completamente justo"                                                                                                                                                     , "w01-w04"              , "Variable X (análisis exploratorio)" ,
  "d02_02"        , "Justicia distributiva"  , "Percepción de justicia en el sistema de educación en Chile"                                                                                                                                                           , "1=Completamente injusto; 5=Completamente justo"                                                                                                                                                     , "w01-w04"              , "Variable X (análisis exploratorio)" ,
  "d02_03"        , "Justicia distributiva"  , "Percepción de justicia en el sistema de salud en Chile"                                                                                                                                                               , "1=Completamente injusto; 5=Completamente justo"                                                                                                                                                     , "w01-w04"              , "Variable X (análisis exploratorio)" ,

  # --- Variables creadas ---
  "brecha_perc"   , "Desigualdad (creada)"   , "Brecha salarial percibida: logaritmo natural de la razón entre el salario percibido del mejor y peor pagado. Calculada en cada ola como log(d03_01 / d03_02). Valores positivos indican mayor desigualdad percibida." , "Numérico continuo (log-ratio)"                                                                                                                                                                      , "w01-w07"              , "Variable X (RI-CLPM)"               ,
  "brecha_just"   , "Desigualdad (creada)"   , "Brecha salarial justa: logaritmo natural de la razón entre el salario justo del mejor y peor pagado. Calculada en cada ola como log(d04_01 / d04_02). Valores positivos indican mayor tolerancia a la desigualdad."   , "Numérico continuo (log-ratio)"                                                                                                                                                                      , "w01-w07"              , "Variable X (RI-CLPM)"               ,
  "ideol4"        , "Política (creada)"      , "Ideología política del encuestado en cuatro categorías, creada a partir de c15_w01"                                                                                                                                   , "1=Izquierda (c15: 0-3); 2=Centro (c15: 4-6); 3=Derecha (c15: 7-10); 4=Ninguno/NS/NR (c15: 11-12)"                                                                                                   , "w01 (time-invariant)" , "Moderador"                          ,
  "ideol2"        , "Política (creada)"      , "Ideología política del encuestado como variable binaria: si se posiciona o no en el espectro político, creada a partir de c15_w01"                                                                                    , "0=No se posiciona (c15: 11-12); 1=Se posiciona (c15: 0-10)"                                                                                                                                         , "w01 (time-invariant)" , "Moderador"
)

# 3. Save Excel -----------------------------------------------------------

write_xlsx(
  list("Metadata variables" = metadata),
  "input/other/metadata_variables.xlsx"
)

message("Metadata guardada en input/other/metadata_variables.xlsx")
